# Generated by Django 4.1.1 on 2022-09-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devs", "0002_tag_review_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="vote_ratio",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="vote_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
